name: Publish release to crates.io

on:
  release:
    types:
      - published

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    environment: release
    container: paritytech/ci-unified:bullseye-1.79.0
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Publish Crate
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p parity-scale-codec-derive
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p parity-scale-codec
